org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.41-beta

mod_id=magic_io
mod_name=魔法接口
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=com.yhzcake.magicio
